"use strict";
const STORAGE={api:"learnSomething.youtubeApiKey",history:"learnSomething.history",shown:"learnSomething.shownIds",rejected:"learnSomething.rejectedChannels"};
const labels={useful:"Useful",interesting:"Interesting",stretch:"Stretch",surprise:"Surprise me"};
const ranges={"20-40":{min:20,max:40,label:"20–40 minutes"},"40-90":{min:40,max:90,label:"40–90 minutes"},"90-240":{min:90,max:240,label:"90 minutes–4 hours"}};
const modifiers={any:["explained","deep dive","full documentary","lecture"],lesson:["complete guide","practical lesson","masterclass","how it works"],lecture:["full lecture","university lecture","course","seminar"],documentary:["full documentary","documentary","history documentary"],interview:["expert interview","long form interview","conversation","podcast"]};
let pools={};
const respected=["mit opencourseware","stanford","harvard","yalecourses","royal institution","veritasium","smartereveryday","practical engineering","wendover productions","real engineering","fall of civilizations","bibleproject","nt wright","computerphile","numberphile","3blue1brown","pbs space time","dw documentary","bbc","freecodecamp","fortnine","the b1m","institution of mechanical engineers","gcn tech","ted-ed","crashcourse"];
const clickbait=["you won't believe","this changes everything","they don't want you to know","shocking","destroyed","obliterated","gone wrong","must watch","before it's deleted","exposed","insane","craziest","secret trick"];
const lowValue=["reaction","highlights","best moments","compilation","ambient","ambience","relaxing music","sleep music","lofi","lo-fi","10 hours","24 hours","shorts compilation","asmr"];
const $=s=>document.querySelector(s),els={duration:$("#duration"),format:$("#format"),freshness:$("#freshness"),discover:$("#discover"),status:$("#status"),setup:$("#setup"),apiInline:$("#apiInline"),saveInline:$("#saveInline"),result:$("#result"),thumb:$("#thumb"),durationBadge:$("#durationBadge"),topicChip:$("#topicChip"),modeChip:$("#modeChip"),captionChip:$("#captionChip"),videoTitle:$("#videoTitle"),channel:$("#channel"),reason:$("#reason"),metrics:$("#metrics"),watch:$("#watch"),another:$("#another"),known:$("#known"),reject:$("#reject"),note:$("#note"),learning:$("#learning"),saveLearning:$("#saveLearning"),history:$("#history"),historyIntro:$("#historyIntro"),settings:$("#settings"),settingsButton:$("#settingsButton"),closeSettings:$("#closeSettings"),apiSettings:$("#apiSettings"),saveSettings:$("#saveSettings"),removeKey:$("#removeKey"),clearHistory:$("#clearHistory"),topicCount:$("#topicCount"),topicSummary:$("#topicSummary")};
const state={video:null,topic:null,loading:false};
function parse(v,f){try{return v?JSON.parse(v):f}catch{return f}}
function arr(k){const v=parse(localStorage.getItem(k),[]);return Array.isArray(v)?v:[]}
function put(k,v){localStorage.setItem(k,JSON.stringify(v))}
function apiKey(){return localStorage.getItem(STORAGE.api)?.trim()||""}
function status(m="",type=""){els.status.textContent=m;els.status.className=`status${type?` ${type}`:""}`}
function random(a){return a[Math.floor(Math.random()*a.length)]}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function mode(){return $('input[name="mode"]:checked').value}
function topicObject(t){return{topic:t[0],query:t[1],why:t[2]}}
function searchText(t,f){return`${t.query} ${random(modifiers[f]||modifiers.any)}`.replace(/\s+/g," ").trim()}
function publishedAfter(f){if(f==="any")return null;const d=new Date();d.setUTCFullYear(d.getUTCFullYear()-(f==="year"?1:5));return d.toISOString()}
function minutes(iso){const m=iso.match(/P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);if(!m)return 0;return Number(m[1]||0)*1440+Number(m[2]||0)*60+Number(m[3]||0)+Number(m[4]||0)/60}
function duration(n){const s=Math.round(n*60),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`:`${m}:${String(sec).padStart(2,"0")}`}
function compact(n){return new Intl.NumberFormat("en-GB",{notation:"compact",maximumFractionDigits:1}).format(Number(n||0))}
function age(d){return Math.max(1,(Date.now()-new Date(d).getTime())/86400000)}
function caps(title){const letters=title.replace(/[^a-z]/gi,"");return letters?letters.replace(/[^A-Z]/g,"").length/letters.length:0}
function score(v,r,f){const title=v.snippet.title.toLowerCase(),channel=v.snippet.channelTitle.toLowerCase(),views=Number(v.statistics?.viewCount||0),likes=Number(v.statistics?.likeCount||0),comments=Number(v.statistics?.commentCount||0),vpd=views/age(v.snippet.publishedAt),mid=(r.min+r.max)/2;let s=Math.log10(views+10)*5+Math.log10(vpd+1)*7+Math.log10(likes+1)*1.5+Math.log10(comments+1)+Math.max(0,8-Math.abs(v.durationMinutes-mid)/Math.max(10,mid)*8);if(v.contentDetails?.caption==="true")s+=5;if(v.contentDetails?.definition==="hd")s++;if(respected.some(n=>channel.includes(n)))s+=10;if(/lecture|documentary|course|seminar|masterclass|explained|engineering|history|science/.test(title))s+=3;if(f==="interview"&&/interview|conversation|podcast/.test(title))s+=4;if(f==="documentary"&&/documentary/.test(title))s+=5;if(f==="lecture"&&/lecture|course|seminar/.test(title))s+=5;if(f==="lesson"&&/guide|lesson|masterclass|how to|explained/.test(title))s+=4;if(clickbait.some(p=>title.includes(p)))s-=10;if(lowValue.some(p=>title.includes(p)))s-=18;if(caps(v.snippet.title)>.55&&v.snippet.title.length>18)s-=7;if((v.snippet.title.match(/!/g)||[]).length>2)s-=4;if(arr(STORAGE.rejected).map(x=>x.toLowerCase()).includes(channel))s-=50;if(arr(STORAGE.shown).includes(v.id))s-=100;return s}
async function json(url){const res=await fetch(url),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`YouTube request failed (${res.status}).`);return data}
async function youtube(key,q,fresh){const p=new URLSearchParams({part:"snippet",q,key,type:"video",maxResults:"25",videoDuration:"long",videoEmbeddable:"true",safeSearch:"moderate",relevanceLanguage:"en",regionCode:"GB",order:"relevance"}),after=publishedAfter(fresh);if(after)p.set("publishedAfter",after);const search=await json(`https://www.googleapis.com/youtube/v3/search?${p}`),ids=(search.items||[]).map(x=>x.id?.videoId).filter(Boolean);if(!ids.length)return[];const d=new URLSearchParams({part:"snippet,contentDetails,statistics,status",id:ids.join(","),key}),details=await json(`https://www.googleapis.com/youtube/v3/videos?${d}`);return(details.items||[]).map(v=>({...v,durationMinutes:minutes(v.contentDetails?.duration||"")}))}
function choose(videos,r,f){const good=videos.filter(v=>v.status?.embeddable!==false&&v.durationMinutes>=r.min&&v.durationMinutes<=r.max&&!lowValue.some(p=>v.snippet.title.toLowerCase().includes(p))).map(v=>({...v,learningScore:score(v,r,f)})).sort((a,b)=>b.learningScore-a.learningScore);if(!good.length)return null;const short=good.slice(0,Math.min(6,good.length)),weighted=short.flatMap((v,i)=>Array(Math.max(1,short.length-i)).fill(v));return random(weighted)}
function remember(id){const shown=arr(STORAGE.shown).filter(x=>x!==id);shown.unshift(id);put(STORAGE.shown,shown.slice(0,300))}
function entry(kind,note=""){if(!state.video||!state.topic)return null;return{id:state.video.id,title:state.video.snippet.title,channel:state.video.snippet.channelTitle,url:`https://www.youtube.com/watch?v=${state.video.id}`,topic:state.topic.topic,duration:duration(state.video.durationMinutes),status:kind,note,timestamp:new Date().toISOString()}}
function saveHistory(kind,note=""){const e=entry(kind,note);if(!e)return;const h=arr(STORAGE.history).filter(x=>x.id!==e.id);h.unshift(e);put(STORAGE.history,h.slice(0,30));renderHistory()}
function renderHistory(){const h=arr(STORAGE.history).slice(0,5);els.history.replaceChildren();els.historyIntro.hidden=h.length>0;h.forEach(x=>{const li=document.createElement("li"),div=document.createElement("div"),a=document.createElement("a"),small=document.createElement("small"),badge=document.createElement("span");a.href=x.url;a.target="_blank";a.rel="noopener noreferrer";a.textContent=x.title;small.textContent=`${x.topic} · ${x.duration}${x.note?` · “${x.note}”`:""}`;badge.className="chip";badge.textContent=x.status==="watched"?"Watched":x.status==="known"?"Known":"Rejected";div.append(a,small);li.append(div,badge);els.history.append(li)})}
function render(v,t,m){state.video=v;state.topic=t;remember(v.id);els.thumb.src=v.snippet.thumbnails?.maxres?.url||v.snippet.thumbnails?.standard?.url||v.snippet.thumbnails?.high?.url||"";els.thumb.alt=`Thumbnail for ${v.snippet.title}`;els.durationBadge.textContent=duration(v.durationMinutes);els.topicChip.textContent=t.topic;els.modeChip.textContent=labels[m];els.captionChip.hidden=v.contentDetails?.caption!=="true";els.videoTitle.textContent=v.snippet.title;els.channel.textContent=v.snippet.channelTitle;els.reason.textContent=t.why;els.watch.href=`https://www.youtube.com/watch?v=${v.id}`;els.learning.value="";els.note.classList.remove("show");els.metrics.replaceChildren();const published=new Intl.DateTimeFormat("en-GB",{year:"numeric",month:"short"}).format(new Date(v.snippet.publishedAt));[`${compact(v.statistics?.viewCount)} views`,`Published ${published}`,`Quality score ${Math.round(v.learningScore)}`].forEach(x=>{const s=document.createElement("span");s.textContent=x;els.metrics.append(s)});els.setup.classList.remove("show");els.result.classList.add("show");els.result.scrollIntoView({behavior:"smooth",block:"start"})}
async function discover(){if(state.loading)return;const key=apiKey();if(!key){els.setup.classList.add("show");els.result.classList.remove("show");status("Add a restricted YouTube API key to begin.","error");els.apiInline.focus();return}state.loading=true;els.discover.disabled=true;els.discover.textContent="Finding something worthwhile…";els.result.classList.remove("show");status("Choosing a subject, filtering long-form results and scoring quality…");const m=mode(),f=els.format.value,fresh=els.freshness.value,r=ranges[els.duration.value],topics=shuffle(pools[m].map(topicObject));let last=null;try{for(const t of topics.slice(0,3)){try{const candidate=choose(await youtube(key,searchText(t,f),fresh),r,f);if(candidate){render(candidate,t,m);status("One result selected. Watch it or reject it; do not browse the feed.","success");return}}catch(e){last=e;break}}if(last)throw last;status(`No strong match landed inside ${r.label}. Try another format, age range or duration.`,"error")}catch(e){console.error(e);const keyProblem=/api key|keyInvalid|forbidden|referer|quota/i.test(e.message);status(keyProblem?`API key problem: ${e.message}`:`Could not reach YouTube: ${e.message}`,"error");if(keyProblem)els.setup.classList.add("show")}finally{state.loading=false;els.discover.disabled=false;els.discover.textContent="Teach me something"}}
function saveKey(input){const key=input.value.trim();if(!key){status("Paste an API key before saving.","error");input.focus();return}localStorage.setItem(STORAGE.api,key);els.apiInline.value="";els.apiSettings.value="";els.setup.classList.remove("show");status("API key saved on this device. Ready.","success");if(els.settings.open)els.settings.close()}
els.discover.addEventListener("click",discover);els.another.addEventListener("click",discover);
els.watch.addEventListener("click",()=>{saveHistory("watched");els.note.classList.add("show");setTimeout(()=>els.learning.focus(),80)});
els.known.addEventListener("click",()=>{saveHistory("known");status("Marked as already known. Finding a different direction…");discover()});
els.reject.addEventListener("click",()=>{saveHistory("rejected");if(state.video){const c=arr(STORAGE.rejected),name=state.video.snippet.channelTitle;if(!c.includes(name)){c.push(name);put(STORAGE.rejected,c.slice(-50))}}status("Rejected. That channel will be strongly penalised in future selections.");discover()});
els.saveLearning.addEventListener("click",()=>{const n=els.learning.value.trim();if(!n){els.learning.focus();return}saveHistory("watched",n);status("Learning note saved on this device.","success");els.learning.value="";els.note.classList.remove("show")});
els.learning.addEventListener("keydown",e=>{if(e.key==="Enter")els.saveLearning.click()});
els.saveInline.addEventListener("click",()=>saveKey(els.apiInline));els.saveSettings.addEventListener("click",()=>saveKey(els.apiSettings));els.apiInline.addEventListener("keydown",e=>{if(e.key==="Enter")els.saveInline.click()});
els.settingsButton.addEventListener("click",()=>{els.apiSettings.placeholder=apiKey()?"API key saved — paste to replace":"Paste API key";els.settings.showModal()});els.closeSettings.addEventListener("click",()=>els.settings.close());els.settings.addEventListener("click",e=>{if(e.target===els.settings)els.settings.close()});
els.removeKey.addEventListener("click",()=>{localStorage.removeItem(STORAGE.api);els.setup.classList.add("show");status("API key removed from this device.");els.settings.close()});
els.clearHistory.addEventListener("click",()=>{localStorage.removeItem(STORAGE.history);localStorage.removeItem(STORAGE.shown);localStorage.removeItem(STORAGE.rejected);renderHistory();status("Local learning history cleared.");els.settings.close()});
async function init(){try{const response=await fetch("topics-v2.json");if(!response.ok)throw new Error(`Topic library failed (${response.status}).`);pools=await response.json();const counts=Object.fromEntries(Object.entries(pools).map(([k,v])=>[k,v.length]));els.topicCount.textContent=`${Object.values(counts).reduce((a,b)=>a+b,0)} routes across four pools`;els.topicSummary.textContent=`Useful: ${counts.useful}. Interesting: ${counts.interesting}. Stretch: ${counts.stretch}. Surprise me: ${counts.surprise}.`;els.discover.disabled=false;status("")}catch(error){console.error(error);status("The topic library could not be loaded. Refresh the page.","error")}renderHistory();if(!apiKey())els.setup.classList.add("show")}els.discover.disabled=true;init();
